apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      name: kibana
  type: {{ .Values.service.type }}