apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.service.grpcPort }}
          http:
            endpoint: 0.0.0.0:{{ .Values.service.port }}
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
    extensions:
      health_check:
        endpoint: 0.0.0.0:{{ .Values.service.healthPort }}
    exporters:
      otlp_http/elastic-apm:
        endpoint: http://{{ .Values.apmServer.serviceFQDN }}:{{ .Values.apmServer.port }}
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp_http/elastic-apm]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp_http/elastic-apm]
