apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
    - protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      name: otlp-grpc
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: otlp-http
    - protocol: TCP
      port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}
      name: health
  type: {{ .Values.service.type }}
