### Docker Compose: list beers via gateway
GET http://localhost:{{application-port}}/api/v1/beer/
Accept: application/json

### Docker Compose: list beers direct
GET http://localhost:{{beer-service-port}}/api/v1/beer/
Accept: application/json

### Docker Compose: list beers direct
GET http://host.docker.internal:{{beer-service-port}}/api/v1/beer/
Accept: application/json

### TODO: Kubernetes: list beers direct. here we first need to retrive the random port  with the kubectl get all command
GET http://localhost:31975/api/v1/beer/
Accept: application/json
