### get beers
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v1/beer
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=kbe-brewery-gateway

### get customers
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v1/customers/?
    pageNumber={{$random.integer(100)}}&
    pageSize={{$random.integer(100)}}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=kbe-brewery-gateway

