global:
  namespace: kbe-brewery-gateway

service:
  type: NodePort

  port: 5601
  targetPort: 5601
  nodePort: 30561

elasticsearch:
  service:
    port: 9200
    serviceFQDN: "kbe-brewery-gateway-elasticsearch.kbe-brewery-gateway.svc.cluster.local"

ingress:
  enabled: false

kibanaImage:
  repository: docker.elastic.co/kibana/kibana
  tag: "7.17.29"
  pullPolicy: IfNotPresent

curlimagesImage:
  repository: curlimages/curl
  tag: "7.87.0"
  pullPolicy: IfNotPresent

busyboxImage:
  repository: busybox
  tag: "1.37.0"
  pullPolicy: IfNotPresent
