apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
data:
  filebeat.yml: |-
    #logging.level: debug

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config.enabled: false
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*.log
          templates:
            - config:
                - type: container
                  paths:
                    - /var/log/containers/*.log
                  processors:
                    - decode_json_fields:
                        fields: ["message"]
                        target: ""
                        overwrite_keys: true
    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}