apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "filebeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "filebeat.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "filebeat.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: wait-for-kibana
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z {{ .Values.kibana.service.serviceFQDN }} {{ .Values.kibana.service.port }}; do echo "[busybox: wait-for-kibana] waiting for kibana"; sleep 2; done; echo "[busybox: wait-for-kibana] kibana is available"' ]
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.17.28
          imagePullPolicy: IfNotPresent
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }}
            - name: ELASTICSEARCH_PORT
              value: {{ .Values.elasticsearch.port | quote }}
            - name: ELASTICSEARCH_USERNAME
              value: {{ .Values.elasticsearch.username }}
            - name: ELASTICSEARCH_PASSWORD
              value: {{ .Values.elasticsearch.password }}
            - name: ELASTIC_CLOUD_ID
              value: {{ .Values.elasticCloud.id }}
            - name: ELASTIC_CLOUD_AUTH
              value: {{ .Values.elasticCloud.auth }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: {{ include "filebeat.fullname" . }}-config
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}