apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
      {{- include "filebeat.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "filebeat.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "filebeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]