apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elasticsearch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: elasticsearch
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "elasticsearch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{.Values.elasticsearchImage.repository }}:{{.Values.elasticsearchImage.tag }}
          imagePullPolicy: {{.Values.elasticsearchImage.pullPolicy }}
          resources: {}
          env:
            - name: discovery.type
              value: single-node
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: transport
              containerPort: {{ .Values.service.transport }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3