global:
  namespace: kbe-brewery-gateway

service:
  type: NodePort

  port: 8200
  targetPort: 8200
  nodePort: 30820

elasticsearch:
  serviceFQDN: "kbe-brewery-gateway-elasticsearch.kbe-brewery-gateway.svc.cluster.local"
  port: 9200

kibana:
  serviceFQDN: "kbe-brewery-gateway-kibana.kbe-brewery-gateway.svc.cluster.local"
  port: 5601

apmServerImage:
  repository: docker.elastic.co/apm/apm-server
  tag: "9.5.2"
  pullPolicy: IfNotPresent

curlimagesImage:
  repository: curlimages/curl
  tag: "8.21.0"
  pullPolicy: IfNotPresent

resources: {}
